version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker.io/stephenlautier/netcore-docker-ci:4.0.1-net5
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - run:
          name: Print environment versions
          command: |
            NPM_V=$(npm -v)
            echo npm version':' $NPM_V
            DOTNET_CLI_V=$(dotnet --version)
            echo dotnet cli version':' $DOTNET_CLI_V
      - checkout
      - run:
          name: Restore and build
          command: |
            . ./.circleci/utils.sh
            eval $(parse_yaml ./tools/app-config.yml "CONFIG_")

            echo -e "\e[36m ---- restore packages ---- \e[39m"
            dotnet restore $CONFIG_SOLUTION /p:Configuration=Release

            echo -e "\e[36m ---- dotnet build ---- \e[39m"
            dotnet build $CONFIG_SOLUTION -c Release
      - run:
          name: test
          command: npm test
      - run:
          name: Check if branch is publishable
          command: |
            if ! ([ $CIRCLE_BRANCH = "develop" ] || [ $CIRCLE_BRANCH = "master" ]); then
              echo "Non-publishable branch; finishing build..."
              circleci step halt
            fi
      - deploy:
          name: Publish NuGet
          command: |
            if [ "$CIRCLE_BRANCH" != "master" ]; then
              echo -e "\e[33m Branch does not publish -- exit!"
              exit
            fi

            export SKETCH7_NUGET_API_KEY=$API_KEY

            npm run publish:dev